package com.example.airsick;

public class CityList {

    private static final String[] LIST_OF_CITIES = {
            "Vancouver",
            "Tokyo",
            "Delhi",
            "Shanghai",
            "Sao Paulo",
            "Mexico City",
            "Beijing",
            "Mumbai",
            "Osaka",
            "Karachi",
            "Istanbul",
            "Buenos Aires",
            "Kolkata",
            "Lagos",
            "Manila",
            "Tianjin",
            "Guangzhou",
            "Lahore",
            "Bangalore",
            "Moscow",
            "Shenzhen",
            "Chennai",
            "Bogota",
            "Paris",
            "Jakarta",
            "Lima",
            "Bangkok",
            "Hyderabad",
            "Seoul",
            "Nagoya",
            "London",
            "Chengdu",
            "Tehran",
            "Nanjing",
            "Ho Chi Minh City",
            "Wuhan",
            "Ahmedabad",
            "New York City",
            "Kuala Lumpur",
            "Hangzhou",
            "Hong Kong",
            "Dongguan",
            "Suzhou",
            "Foshan",
            "Riyadh",
            "Shenyang",
            "Baghdad",
            "Santiago",
            "Pune",
            "Madrid",
            "Haerbin",
            "Toronto",
            "Singapore",
            "Khartoum",
            "Johannesburg",
            "Dalian",
            "Qingdao",
            "Barcelona",
            "Fukuoka",
            "Dublin",
            "Saint Petersburg",
            "Yangon",
            "Alexandria",
            "Abidjan",
            "Guadalajara",
            "Ankara",
            "Vatican City",
            "Melbourne",
            "Addis Ababa",
            "Sydney",
            "Monterrey",
            "Hanoi",
            "Brasilia",
            "Cape Town",
            "Regina",
            "Changsha",
            "Kunming",
            "Urumqi",
            "Changchun",
            "Brussels",
            "Yellowknife",
            "Portland",
            "Kabul",
            "Houston",
            "Ningbo",
            "Tel Aviv",
            "Montreal",
            "Edmonton"
    };

    public static String[] getListOfCities() {
        return LIST_OF_CITIES;
    }
}

//    private static final String[] LIST_OF_CITIES = {
//            "Vancouver",
//            "Tokyo",
//            "Delhi",
//            "Shanghai",
//            "Sao Paulo",
//            "Mexico City",
//            "Dhaka",
//            "Cairo",
//            "Beijing",
//            "Mumbai",
//            "Osaka",
//            "Karachi",
//            "Istanbul",
//            "Buenos Aires",
//            "Kolkata",
//            "Kinshasa",
//            "Lagos",
//            "Manila",
//            "Tianjin",
//            "Guangzhou",
//            "Rio de Janeiro",
//            "Lahore",
//            "Bangalore",
//            "Moscow",
//            "Shenzhen",
//            "Chennai",
//            "Bogota",
//            "Paris",
//            "Jakarta",
//            "Lima",
//            "Bangkok",
//            "Hyderabad",
//            "Seoul",
//            "Nagoya",
//            "London",
//            "Chengdu",
//            "Tehran",
//            "Nanjing",
//            "Ho Chi Minh City",
//            "Luanda",
//            "Wuhan",
//            "Xi-an Shaanxi",
//            "Ahmedabad",
//            "New York City",
//            "Kuala Lumpur",
//            "Hangzhou",
//            "Hong Kong",
//            "Surat",
//            "Dongguan",
//            "Suzhou",
//            "Foshan",
//            "Riyadh",
//            "Shenyang",
//            "Baghdad",
//            "Dar es Salaam",
//            "Santiago",
//            "Pune",
//            "Madrid",
//            "Haerbin",
//            "Toronto",
//            "Belo Horizonte",
//            "Singapore",
//            "Khartoum",
//            "Johannesburg",
//            "Dalian",
//            "Qingdao",
//            "Barcelona",
//            "Fukuoka",
//            "Ji-nan Shandong",
//            "Zhengzhou",
//            "Saint Petersburg",
//            "Yangon",
//            "Alexandria",
//            "Abidjan",
//            "Guadalajara",
//            "Ankara",
//            "Chittagong",
//            "Melbourne",
//            "Addis Ababa",
//            "Sydney",
//            "Monterrey",
//            "Nairobi",
//            "Hanoi",
//            "Brasilia",
//            "Cape Town",
//            "Jiddah",
//            "Changsha",
//            "Kunming",
//            "Urumqi",
//            "Changchun",
//            "Xinbei",
//            "Shantou",
//            "Hefei",
//            "Kabul",
//            "Rome",
//            "Ningbo",
//            "Tel Aviv",
//            "Montreal",
//            "Edmonton"
//    };
