package com.example.airsick;

/**
 * CityList is a hardcoded list of many of the largest cities around the world
 * it also includes some major cities across Canada. This is used because there were
 * no free APIs available that would allow us to get a list of cities and their data
 * while staying within their request limits.
 */
public class CityList {

    private static final String[] LIST_OF_CITIES = {

            "Tokyo",
            "Delhi",
            "Shanghai",
            "Sao Paulo",
            "Mexico City",
            "Dhaka",
            "Cairo",
            "Beijing",
            "Mumbai",
            "Osaka",
            "Karachi",
            "Chongqing",
            "Istanbul",
            "Buenos Aires",
            "Kolkata",
            "Kinshasa",
            "Lagos",
            "Manila",
            "Tianjin",
            "Guangzhou",
            "Rio de Janeiro",
            "Lahore",
            "Bangalore",
            "Moscow",
            "Shenzhen",
            "Chennai",
            "Bogota",
            "Paris",
            "Jakarta",
            "Lima",
            "Bangkok",
            "Hyderabad",
            "Seoul",
            "Nagoya",
            "London",
            "Chengdu",
            "Tehran",
            "Nanjing",
            "Ho Chi Minh City",
            "Luanda",
            "Wuhan",
            "Xi-an Shaanxi",
            "Ahmedabad",
            "New York City",
            "Kuala Lumpur",
            "Hangzhou",
            "Hong Kong",
            "Surat",
            "Dongguan",
            "Suzhou",
            "Foshan",
            "Riyadh",
            "Shenyang",
            "Baghdad",
            "Dar es Salaam",
            "Santiago",
            "Pune",
            "Madrid",
            "Haerbin",
            "Toronto",
            "Belo Horizonte",
            "Singapore",
            "Khartoum",
            "Johannesburg",
            "Dalian",
            "Qingdao",
            "Barcelona",
            "Fukuoka",
            "Ji-nan Shandong",
            "Zhengzhou",
            "Saint Petersburg",
            "Yangon",
            "Alexandria",
            "Abidjan",
            "Guadalajara",
            "Ankara",
            "Chittagong",
            "Melbourne",
            "Addis Ababa",
            "Sydney",
            "Monterrey",
            "Nairobi",
            "Hanoi",
            "Brasilia",
            "Cape Town",
            "Jiddah",
            "Changsha",
            "Kunming",
            "Urumqi",
            "Changchun",
            "Xinbei",
            "Shantou",
            "Hefei",
            "Kabul",
            "Rome",
            "Ningbo",
            "Tel Aviv",
            "Montreal",
            "Shijiazhuang",
            "Recife",
            "Yaounde",
            "Porto Alegre",
            "Fortaleza",
            "Kano",
            "Medellin",
            "Jaipur",
            "Los Angeles",
            "Taiyuan Shanxi",
            "Nanning",
            "Ekurhuleni",
            "Salvador",
            "Casablanca",
            "Douala",
            "Xiamen",
            "Lucknow",
            "Fuzhou Fujian",
            "Changzhou",
            "Kozhikode",
            "Curitiba",
            "Wenzhou",
            "Nanchang",
            "Ibadan",
            "Malappuram",
            "Berlin",
            "Tangshan Hebei",
            "Faisalabad",
            "Antananarivo",
            "Bekasi",
            "Kumasi",
            "Kampala",
            "Busan",
            "Abuja",
            "Guiyang",
            "Asuncion",
            "Santo Domingo",
            "Campinas",
            "Wuxi",
            "Mashhad",
            "Puebla",
            "Dakar",
            "Thrissur",
            "Kochi",
            "Kuwait City",
            "Durban",
            "Port Harcourt",
            "Lanzhou",
            "Kanpur",
            "Athens",
            "Milan",
            "Indore",
            "Pyongyang",
            "Sanaa",
            "Guayaquil",
            "Izmir",
            "Kiev",
            "Guatemala City",
            "Surabaya",
            "Lisbon",
            "Caracas",
            "Zhongshan",
            "Nagpur",
            "Shizuoka",
            "Dubai",
            "Ouagadougou",
            "Lusaka",
            "Coimbatore",
            "Port-au-Prince",
            "Depok",
            "Handan",
            "Incheon",
            "Cali",
            "Algiers",
            "Huaian",
            "Manchester",
            "Vancouver",
            "Yellowknife",
            "Regina",
            "Hamilton",
            "Burnaby"
    };

    public static String[] getListOfCities() {
        return LIST_OF_CITIES;
    }
}
